CREATE TABLE TB_FILMES
(
ID int primary key,
GENERO int,
TITULO varchar(100),
SINOPSE VARCHAR (1000),
PRODUTORA VARCHAR(20),
DATA_LANCAMENTO DATETIME,
DURACAO INT,
STATUS_FILME INT,
STATUS_REGISTRO BIT
)